// This file was auto-generated by ML.NET Model Builder. 

using System;
using RecomendedMoviesML.Model;

namespace RecomendedMoviesML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                MovieId = 1097F,
                Timestamp = 9.649817E+08F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual UserId with predicted UserId from sample data...\n\n");
            Console.WriteLine($"MovieId: {sampleData.MovieId}");
            Console.WriteLine($"Timestamp: {sampleData.Timestamp}");
            Console.WriteLine($"\n\nPredicted UserId: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
